version: '3.9'
services:
  #mqttbroker:
    #image: eclipse-mosquitto:1.6.13
    #restart: unless-stopped
    #ports: 
      #- "1883:1883"
      
  nr-controller:   
    public: true
    hostname: nr-controller
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=NR-Controller-ns0
        - NR_DB_USER=${USER}
        - NR_DB_PASS=${PASS}
        - NR_DB_HOST=${HOST}
        - NR_NAMESPACE=${OKTETO_NAMESPACE}
        - NR_IP=${BUILDKIT_HOST}
        - NR_TYPE=ControllerPackage.json 
    ports:
      - 1880
      - "9229:9229"
    expose:
      - 1883
    links:
      - mqttbroker
